[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "nft"

# Environment variables untuk Netlify Functions
[context.production.environment]
  MQTT_BROKER = "mqtts://4bbdfa736ca64112bb38a14789942a8a.s1.eu.hivemq.cloud"
  MQTT_PORT = "8883"
  MQTT_USER = "pepeq123"
  MQTT_PASS = "123098@Qwe"

[context.deploy-preview.environment]
  MQTT_BROKER = "mqtts://4bbdfa736ca64112bb38a14789942a8a.s1.eu.hivemq.cloud"
  MQTT_PORT = "8883"
  MQTT_USER = "pepeq123"
  MQTT_PASS = "123098@Qwe"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
